#!/bin/bash
# chmod ug+x zip
clear

echo 'Creating WordPress Plugin zip...'
echo '(Takes a couple of minutes)'

rm -rf ~/Desktop/listingslab
cp -r ~/Desktop/Node/listingslab ~/Desktop/

rm -rf ~/Desktop/listingslab/.git
rm -rf ~/Desktop/listingslab/.github
rm -rf ~/Desktop/listingslab/.gitignore
rm -rf ~/Desktop/listingslab/node_modules
rm -rf ~/Desktop/listingslab/listingslab.zip
rm -rf ~/Desktop/listingslab/yarn.lock

rm -rf ~/Desktop/listingslab/react/pwa/yarn.lock
rm -rf ~/Desktop/listingslab/react/pwa/package.json
rm -rf ~/Desktop/listingslab/react/pwa/.env.production
rm -rf ~/Desktop/listingslab/react/pwa/.env.development
rm -rf ~/Desktop/listingslab/react/pwa/.gitignore
rm -rf ~/Desktop/listingslab/react/pwa/src
rm -rf ~/Desktop/listingslab/react/pwa/public
rm -rf ~/Desktop/listingslab/react/pwa/node_modules

rm -rf ~/Desktop/listingslab/react/wp-admin/.gitignore
rm -rf ~/Desktop/listingslab/react/wp-admin/yarn.lock
rm -rf ~/Desktop/listingslab/react/wp-admin/node_modules
rm -rf ~/Desktop/listingslab/react/wp-admin/package.json
rm -rf ~/Desktop/listingslab/react/wp-admin/.env.production
rm -rf ~/Desktop/listingslab/react/wp-admin/.env.development
rm -rf ~/Desktop/listingslab/react/wp-admin/src
rm -rf ~/Desktop/listingslab/react/wp-admin/public

rm -rf ~/Desktop/listingslab/unix
rm -rf ~/Desktop/listingslab/package.json
cd ~/Desktop 

zip -r listingslab.zip listingslab

mv listingslab.zip ~/Desktop/Node/listingslab

rm -rf ~/Desktop/listingslab
